# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  nixpkgs.hostPlatform = "x86_64-linux";

  services.fwupd.enable = true;
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  boot.initrd.availableKernelModules = ["nvme" "usb_storage" "usbhid" "thunderbolt" "xhci_pci" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  boot.loader.systemd-boot.enable = lib.mkDefault true;
  boot.loader.efi.canTouchEfiVariables = true;

  hardware.graphics = {
    enable = lib.mkDefault true;
    enable32Bit = lib.mkDefault true;
  };

  hardware.amdgpu.initrd.enable = lib.mkDefault true;

  # allow remote deploy on aarch64 systems
  boot.binfmt.emulatedSystems = ["aarch64-linux"];

  networking.firewall.enable = true;
  networking.nftables.enable = true;
  networking.useDHCP = lib.mkDefault false;
  networking.wireless.enable = lib.mkDefault false;
  networking.networkmanager.enable = false;
  systemd.network.enable = true;
  systemd.network.networks."10-ethernet-dhcp" = {
    enable = true;
    matchConfig.Name = "enp194s0"; # Your Ethernet interface name
    networkConfig = {
      DHCP = "ipv4";
      IPv6AcceptRA = true; # Optional: for IPv6 SLAAC
    };
    linkConfig.RequiredForOnline = "yes"; # Optional
  };
}
# enp246s0f0u2

