repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: gitleaks
        entry: gitleaks protect --verbose --redact --staged
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: commitlint
        name: commitlint
        entry: commitlint --edit
        language: system
        stages: [commit-msg]
