# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  nixpkgs.hostPlatform = "aarch64-linux";

  services.fwupd.enable = true;
  hardware.enableRedistributableFirmware = true;
  boot.initrd.availableKernelModules = ["nvme" "usb_storage" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  boot.loader.systemd-boot.enable = lib.mkDefault true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.firewall.enable = true;
  networking.nftables.enable = true;
  networking.useDHCP = lib.mkDefault false;
  networking.wireless.enable = lib.mkDefault false;
  networking.networkmanager.enable = false;
  systemd.network.enable = true;
  systemd.network.networks."10-ethernet-dhcp" = {
    enable = true;
    matchConfig.Name = "enp1s0";
    networkConfig = {
      DHCP = "ipv4";
      IPv6AcceptRA = true; # Optional: for IPv6 SLAAC
    };
  };
}
