# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  services.fwupd.enable = true;
  hardware.enableRedistributableFirmware = true;
  boot.initrd.availableKernelModules = ["nvme" "usb_storage" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  boot.loader.systemd-boot.enable = lib.mkDefault true;
  boot.loader.efi.canTouchEfiVariables = true;

  networking.firewall.enable = true;
  networking.nftables.enable = true;
  systemd.network.wait-online.enable = false;
  systemd.network = {
    enable = true;
    netdevs = {
      "20-vlan2" = {
        netdevConfig = {
          Kind = "vlan";
          Name = "vlan2";
        };
        vlanConfig.Id = 2;
      };
    };
    networks = {
      "30-manage" = {
        matchConfig.Name = "enp1s0";
        networkConfig.DHCP = false;
        dns = ["10.55.10.35"];
        vlan = ["vlan2"];
        linkConfig.RequiredForOnline = "carrier";
      };
      "40-svc" = {
        matchConfig.Name = "vlan2";
        address = ["10.55.20.25/24"];
        gateway = ["10.55.20.1"];
      };
    };
  };
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault false;
  networking.wireless.enable = false;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
