# Ruinage Direnv Integration
#
# This module generates direnv snippets for projects with direnv.enable = true.
# For each project:
# - Generates snippet at ~/.config/direnv/envrc.d/<name>.sh
# - Auto-injects into .envrc.local if direnv.autoInject = true
#
# Snippet format sources environmentFiles using direnv's dotenv command.
#
# NOTE: The `opencode` wrapper function is now generated by fish.nix as a native
# fish function, not as a bash function in the direnv snippet. This allows the
# wrapper to work correctly when sourced directly in fish shell.
{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.ruinous.ruinage;
  ruinageLib = import ../../../../lib/ruinage/wrapper.nix { inherit lib pkgs; };

  # Filter projects that have direnv enabled
  projectsWithDirenv = filterAttrs (_: p:
    p.direnv.enable && (p.environmentFiles != [] || cfg.environmentFiles != [])
  ) cfg.projects;

  # Generate direnv snippet for a project
  # Snippet uses direnv's dotenv command to load environment files
  mkDirenvSnippet = name: project: let
    # Combine global and per-project env files
    allEnvFiles = cfg.environmentFiles ++ project.environmentFiles;
    # Extract secret names from paths (e.g., /path/to/agenix/secret_name -> secret_name)
    secretNames = map (p: baseNameOf (toString p)) allEnvFiles;
    # Generate dotenv commands for each secret
    dotenvCommands = concatMapStringsSep "\n" (secretName: ''
      # Load ${secretName} if available
      if [[ -f "${cfg.direnv.secretsDir}/${secretName}" ]]; then
        dotenv "${cfg.direnv.secretsDir}/${secretName}"
      fi'') secretNames;
  in ''
    # Auto-generated direnv snippet for project: ${name}
    # Source this in your project's .envrc:
    #   source_env ~/.config/direnv/envrc.d/${name}.sh
    #
    # Or add to .envrc.local:
    #   source ~/.config/direnv/envrc.d/${name}.sh
    #
    # NOTE: The opencode wrapper function is provided as a native fish function
    # (see ruinage/fish.nix), not via this direnv snippet.

    ${dotenvCommands}
  '';
in {
  # Auto-enable when any project has direnv enabled, or when explicitly enabled
  config = mkIf (cfg.direnv.enable || projectsWithDirenv != {}) {
    # Generate direnv snippets in ~/.config/direnv/envrc.d/
    xdg.configFile = mapAttrs' (name: project:
      nameValuePair "direnv/envrc.d/${name}.sh" {
        text = mkDirenvSnippet name project;
        executable = false;
      }) projectsWithDirenv;

    # Auto-inject source line into .envrc.local for each project
    home.activation.injectDirenvSnippets = lib.mkIf cfg.direnv.autoInject (
      lib.hm.dag.entryAfter ["writeBoundary"] ''
        ${concatMapStringsSep "\n" (name: let
          project = projectsWithDirenv.${name};
          snippetPath = "${config.home.homeDirectory}/.config/direnv/envrc.d/${name}.sh";
          projectPath = ruinageLib.mkProjectPath {
            homeDirectory = config.home.homeDirectory;
            namespace = "ruinage";
            repo = project.repo;
          };
          envrcLocal = "${projectPath}/.envrc.local";
          sourceLine = "source_env ${snippetPath}";
          markerComment = "# ruinage: auto-injected";
        in ''
          # Project: ${name}
          if [ -d "${projectPath}" ]; then
            # Check if .envrc.local exists and already has our source line
            if [ -f "${envrcLocal}" ]; then
              if ! ${pkgs.gnugrep}/bin/grep -qF "${sourceLine}" "${envrcLocal}"; then
                $VERBOSE_ECHO "ruinage: injecting direnv snippet into ${name}/.envrc.local"
                echo "" >> "${envrcLocal}"
                echo "${markerComment}" >> "${envrcLocal}"
                echo "${sourceLine}" >> "${envrcLocal}"
              fi
            else
              $VERBOSE_ECHO "ruinage: creating ${name}/.envrc.local with direnv snippet"
              echo "${markerComment}" > "${envrcLocal}"
              echo "${sourceLine}" >> "${envrcLocal}"
            fi
          fi
        '') (attrNames projectsWithDirenv)}
      ''
    );
  };
}
