# Ruinage Documentation Aggregation
#
# This module provides:
# - Global documentation settings (ruinous.ruinage.docs.*)
# - Per-project documentation configuration (via types.nix)
# - Symlinks pre-built docs from flake input packages
# - Index page generation listing all projects
#
# Architecture:
# - Each project specifies a flake input name and package output
# - Docs packages are referenced directly from flake.inputs
# - Aggregation symlinks these Nix store paths to a central directory
# - Index page provides navigation to all project docs
#
# Note: Caddy configuration should be done at the NixOS level, not home-manager.
# This module exposes the outputDir and project list for use by system-level Caddy config.
#
# Usage:
#   ruinous.ruinage.docs = {
#     enable = true;
#     outputDir = ".local/share/ruinage/docs";
#   };
#
#   ruinous.ruinage.projects.ruinagents = {
#     docs.enable = true;
#     docs.flakeInput = "ruinagents";  # References flake.inputs.ruinagents
#     docs.packageOutput = "docs";      # References .packages.${system}.docs
#     docs.title = "Ruinous Agents";
#   };
{
  config,
  lib,
  pkgs,
  flake,
  ...
}:
with lib; let
  cfg = config.ruinous.ruinage;
  docsCfg = config.ruinous.ruinage.docs;

  # Filter projects with docs.enable = true
  docsProjects = filterAttrs (_: p: p.docs.enable) (cfg.projects or {});

  # Get docs package for a project from flake inputs
  getDocsPackage = name: project: let
    flakeInput = project.docs.flakeInput;
    packageOutput = project.docs.packageOutput;
    inputExists = flake.inputs ? ${flakeInput};
    input = flake.inputs.${flakeInput} or null;
    hasPackages = input != null && input ? packages && input.packages ? ${pkgs.system};
    packages = if hasPackages then input.packages.${pkgs.system} else {};
    hasOutput = packages ? ${packageOutput};
  in
    if inputExists && hasPackages && hasOutput
    then packages.${packageOutput}
    else null;

  # Filter to only projects with valid docs packages
  validDocsProjects = filterAttrs (name: project:
    (getDocsPackage name project) != null
  ) docsProjects;

  # Projects that were enabled but have no valid package
  invalidDocsProjects = filterAttrs (name: project:
    (getDocsPackage name project) == null
  ) docsProjects;

  # Generate index HTML page
  mkIndexHtml = let
    projectLinks = concatMapStringsSep "\n    " (name: let
      project = validDocsProjects.${name};
      title = project.docs.title;
      description = "Documentation for ${title}";
    in ''
      <li><a href="/${name}/">${title}</a> - ${description}</li>'') (attrNames validDocsProjects);
  in ''
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Ruinage Documentation</title>
      <style>
        :root {
          --bg-color: #1a1a2e;
          --text-color: #eaeaea;
          --link-color: #4fc3f7;
          --link-hover: #81d4fa;
          --border-color: #333;
        }
        @media (prefers-color-scheme: light) {
          :root {
            --bg-color: #fafafa;
            --text-color: #333;
            --link-color: #0066cc;
            --link-hover: #0088ff;
            --border-color: #ddd;
          }
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
          max-width: 800px;
          margin: 50px auto;
          padding: 0 20px;
          background-color: var(--bg-color);
          color: var(--text-color);
          line-height: 1.6;
        }
        h1 {
          border-bottom: 2px solid var(--border-color);
          padding-bottom: 10px;
          margin-bottom: 30px;
        }
        ul {
          list-style: none;
          padding: 0;
        }
        li {
          margin: 15px 0;
          padding: 10px;
          border-radius: 5px;
          transition: background-color 0.2s;
        }
        li:hover {
          background-color: rgba(128, 128, 128, 0.1);
        }
        a {
          color: var(--link-color);
          text-decoration: none;
          font-weight: 500;
        }
        a:hover {
          color: var(--link-hover);
          text-decoration: underline;
        }
        .footer {
          margin-top: 50px;
          padding-top: 20px;
          border-top: 1px solid var(--border-color);
          font-size: 0.9em;
          opacity: 0.7;
        }
      </style>
    </head>
    <body>
      <h1>Ruinage Documentation</h1>
      <ul>
        ${projectLinks}
      </ul>
      <div class="footer">
        <p>Generated by <a href="https://github.com/iamruinous/nix-config">ruinage</a></p>
      </div>
    </body>
    </html>
  '';

  # Generate index.html as a derivation
  indexHtml = pkgs.writeText "ruinage-docs-index.html" mkIndexHtml;
in {
  options.ruinous.ruinage.docs = {
    enable = mkEnableOption "Documentation aggregation for ruinage projects";

    outputDir = mkOption {
      type = types.str;
      default = ".local/share/ruinage/docs";
      description = ''
        Directory where aggregated documentation is stored, relative to home directory.
        Will be prefixed with $HOME at runtime.
      '';
      example = ".local/share/ruinage/docs";
    };

    caddy = {
      fqdn = mkOption {
        type = types.str;
        default = "docs.ruinage.ai";
        description = "FQDN for the documentation site (used by system-level Caddy config).";
        example = "docs.example.com";
      };

      port = mkOption {
        type = types.port;
        default = 8080;
        description = "Port for local documentation serving.";
      };
    };
  };

  config = mkIf docsCfg.enable {
    # Warnings for projects with docs.enable but missing flake input/package
    warnings = map (name: let
      project = invalidDocsProjects.${name};
      flakeInput = project.docs.flakeInput;
      packageOutput = project.docs.packageOutput;
    in
      "ruinage-docs: Project '${name}' has docs.enable=true but flake input '${flakeInput}' or package '${packageOutput}' not found"
    ) (attrNames invalidDocsProjects);

    # Activation script to symlink docs and generate index
    home.activation.ruinage-docs = lib.hm.dag.entryAfter ["writeBoundary"] ''
      # Create output directory
      DOCS_OUTPUT_DIR="$HOME/${docsCfg.outputDir}"
      $DRY_RUN_CMD mkdir -p "$DOCS_OUTPUT_DIR"

      # Symlink each project's docs from Nix store
      ${concatMapStringsSep "\n" (name: let
        project = validDocsProjects.${name};
        docsPackage = getDocsPackage name project;
      in ''
        # Project: ${name}
        $VERBOSE_ECHO "ruinage-docs: symlinking ${name} docs"
        $DRY_RUN_CMD rm -f "$DOCS_OUTPUT_DIR/${name}"
        $DRY_RUN_CMD ln -sfn "${docsPackage}" "$DOCS_OUTPUT_DIR/${name}"
      '') (attrNames validDocsProjects)}

      # Symlink index page
      $VERBOSE_ECHO "ruinage-docs: symlinking index.html"
      $DRY_RUN_CMD rm -f "$DOCS_OUTPUT_DIR/index.html"
      $DRY_RUN_CMD ln -sfn "${indexHtml}" "$DOCS_OUTPUT_DIR/index.html"
    '';
  };
}
