# Ruinage Documentation Aggregation
#
# This module provides:
# - Global documentation settings (ruinous.ruinage.docs.*)
# - Per-project documentation configuration (via types.nix)
# - Activation script to symlink pre-built docs from flake outputs
# - Index page generation listing all projects
#
# Architecture:
# - Each project exposes a `<project>-docs` package via its flake.nix
# - Package contains pre-built static HTML (MkDocs site output)
# - Aggregation symlinks these outputs to a central directory
# - Index page provides navigation to all project docs
#
# Note: Caddy configuration should be done at the NixOS level, not home-manager.
# This module exposes the outputDir and project list for use by system-level Caddy config.
#
# Usage:
#   ruinous.ruinage.docs = {
#     enable = true;
#     outputDir = "~/.local/share/ruinage/docs";
#   };
#
#   ruinous.ruinage.projects.nix-config = {
#     docs.enable = true;
#     docs.flakeOutput = "nix-config-docs";
#     docs.title = "NixOS Infrastructure";
#   };
{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.ruinous.ruinage;
  docsCfg = config.ruinous.ruinage.docs;

  # Filter projects with docs.enable = true
  docsProjects = filterAttrs (_: p: p.docs.enable) (cfg.projects or {});

  # Generate index HTML page
  mkIndexHtml = let
    projectLinks = concatMapStringsSep "\n    " (name: let
      project = docsProjects.${name};
      title = project.docs.title;
      # Use project description if available, otherwise generic text
      description = "Documentation for ${title}";
    in ''
      <li><a href="/${name}/">${title}</a> - ${description}</li>'') (attrNames docsProjects);
  in ''
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>Ruinage Documentation</title>
      <style>
        :root {
          --bg-color: #1a1a2e;
          --text-color: #eaeaea;
          --link-color: #4fc3f7;
          --link-hover: #81d4fa;
          --border-color: #333;
        }
        @media (prefers-color-scheme: light) {
          :root {
            --bg-color: #fafafa;
            --text-color: #333;
            --link-color: #0066cc;
            --link-hover: #0088ff;
            --border-color: #ddd;
          }
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif;
          max-width: 800px;
          margin: 50px auto;
          padding: 0 20px;
          background-color: var(--bg-color);
          color: var(--text-color);
          line-height: 1.6;
        }
        h1 {
          border-bottom: 2px solid var(--border-color);
          padding-bottom: 10px;
          margin-bottom: 30px;
        }
        ul {
          list-style: none;
          padding: 0;
        }
        li {
          margin: 15px 0;
          padding: 10px;
          border-radius: 5px;
          transition: background-color 0.2s;
        }
        li:hover {
          background-color: rgba(128, 128, 128, 0.1);
        }
        a {
          color: var(--link-color);
          text-decoration: none;
          font-weight: 500;
        }
        a:hover {
          color: var(--link-hover);
          text-decoration: underline;
        }
        .footer {
          margin-top: 50px;
          padding-top: 20px;
          border-top: 1px solid var(--border-color);
          font-size: 0.9em;
          opacity: 0.7;
        }
      </style>
    </head>
    <body>
      <h1>Ruinage Documentation</h1>
      <ul>
        ${projectLinks}
      </ul>
      <div class="footer">
        <p>Generated by <a href="https://github.com/iamruinous/nix-config">ruinage</a></p>
      </div>
    </body>
    </html>
  '';

  # Helper to get flake reference for a project
  # Projects can specify a full flake reference or just the output name
  getFlakeRef = name: project: let
    flakeOutput = project.docs.flakeOutput;
    # If the project has a repo, construct the flake reference
    # Otherwise, assume it's a local flake output
    hasRepo = project.repo != null;
    forge = project.forge;
    owner = project.owner;
    repo = project.repo;
  in
    if hasRepo
    then "git+ssh://git@${forge}/${owner}/${repo}#${flakeOutput}"
    else ".#${flakeOutput}";
in {
  options.ruinous.ruinage.docs = {
    enable = mkEnableOption "Documentation aggregation for ruinage projects";

    outputDir = mkOption {
      type = types.str;
      default = ".local/share/ruinage/docs";
      description = ''
        Directory where aggregated documentation is stored, relative to home directory.
        Will be prefixed with $HOME at runtime.
      '';
      example = ".local/share/ruinage/docs";
    };

    caddy = {
      fqdn = mkOption {
        type = types.str;
        default = "docs.ruinage.ai";
        description = "FQDN for the documentation site (used by system-level Caddy config).";
        example = "docs.example.com";
      };

      port = mkOption {
        type = types.port;
        default = 8080;
        description = "Port for local documentation serving.";
      };
    };
  };

  config = mkIf ((cfg.enable or false) && docsCfg.enable) {
    # Activation script to symlink docs and generate index
    home.activation.ruinage-docs = lib.hm.dag.entryAfter ["writeBoundary"] ''
      # Create output directory
      DOCS_OUTPUT_DIR="$HOME/${docsCfg.outputDir}"
      $DRY_RUN_CMD mkdir -p "$DOCS_OUTPUT_DIR"

      # Symlink each project's docs
      ${concatMapStringsSep "\n" (name: let
        project = docsProjects.${name};
        flakeRef = getFlakeRef name project;
      in ''
        # Project: ${name}
        $VERBOSE_ECHO "ruinage-docs: checking docs for ${name}"
        
        # Try to build the flake output
        DOCS_PATH=$(${pkgs.nix}/bin/nix build --no-link --print-out-paths "${flakeRef}" 2>/dev/null || true)
        
        if [ -n "$DOCS_PATH" ] && [ -d "$DOCS_PATH" ]; then
          $VERBOSE_ECHO "ruinage-docs: symlinking ${name} docs from $DOCS_PATH"
          $DRY_RUN_CMD rm -f "$DOCS_OUTPUT_DIR/${name}"
          $DRY_RUN_CMD ln -sfn "$DOCS_PATH" "$DOCS_OUTPUT_DIR/${name}"
        else
          echo "Warning: Docs output missing for ${name} (${flakeRef}), skipping"
        fi
      '') (attrNames docsProjects)}

      # Generate index page
      $VERBOSE_ECHO "ruinage-docs: generating index.html"
      $DRY_RUN_CMD cat > "$DOCS_OUTPUT_DIR/index.html" << 'RUINAGE_INDEX_EOF'
${mkIndexHtml}
RUINAGE_INDEX_EOF
    '';
  };
}
