# Ruinous xplr Theme Compositor
# Uses terminal ANSI colors (inherits from wezterm/terminal theme)
{
  lib,
  config,
  ...
}: let
  cfg = config.ruinous.xplr;

  # Minimal xplr config - just set styles using terminal ANSI colors
  # Uses default layout and table columns from xplr
  initLua = ''
    -- xplr configuration generated by Nix
    -- Uses terminal ANSI colors (inherits from wezterm theme)
    version = "1.1.0"

    -- UI Styles
    xplr.config.general.default_ui.style = { fg = "White", bg = "Reset" }
    xplr.config.general.focus_ui.style = { fg = "Black", bg = "Cyan", add_modifiers = { "Bold" } }
    xplr.config.general.selection_ui.style = { fg = "Magenta", add_modifiers = { "Italic" } }
    xplr.config.general.focus_selection_ui.style = { fg = "Black", bg = "Magenta", add_modifiers = { "Bold", "Italic" } }

    -- Node type styles
    xplr.config.node_types.directory.style = { fg = "Blue", add_modifiers = { "Bold" } }
    xplr.config.node_types.file.style = { fg = "White" }
    xplr.config.node_types.symlink.style = { fg = "Cyan", add_modifiers = { "Italic" } }

    -- Panel styles
    xplr.config.general.table.header.style = { fg = "DarkGray" }
    xplr.config.general.panel_ui.default.style = { fg = "Gray", bg = "Reset" }
  '';

in {
  config = lib.mkIf cfg.enable {
    home.file.".config/xplr/init.lua".text = initLua;
  };
}
