# Ruinous xplr Theme Compositor
# Generates xplr init.lua based on N0FRILLS design system
{
  lib,
  config,
  ...
}: let
  cfg = config.ruinous.xplr;

  # Colorway palettes (N0FRILLS)
  colorways = {
    classic = null; # Use default xplr theme
    ruin = {
      bg = "#1c1c1c";
      white = "#eeeeee";
      gray = "#8a8a8a";
      muted = "#626262";
      primary = "#d75fd7";
      highlight = "#5fd7d7";
      accent = "#ffafd7";
      hotAccent = "#ff5faf";
    };
    siege = {
      bg = "#1c1c1c";
      white = "#eeeeee";
      gray = "#8a8a8a";
      muted = "#626262";
      primary = "#875fd7";
      highlight = "#00afaf";
      accent = "#af87ff";
      hotAccent = "#5f5fff";
    };
    ghost = {
      bg = "#1c1c1c";
      white = "#eeeeee";
      gray = "#8a8a8a";
      muted = "#626262";
      primary = "#eeeeee";
      highlight = "#ffaf00";
      accent = "#bcbcbc";
      hotAccent = "#eeeeee";
    };
  };

  palette = colorways.${cfg.themeVariant};

  # Generate Lua code for the palette
  paletteLua = if palette == null then "" else ''
    local c = {
        bg        = "${palette.bg}",
        white     = "${palette.white}",
        gray      = "${palette.gray}",
        muted     = "${palette.muted}",
        primary   = "${palette.primary}",
        highlight = "${palette.highlight}",
        accent    = "${palette.accent}",
        hotAccent = "${palette.hotAccent}",
    }

    -- Apply Styles
    xplr.config.general.style.default = { fg = c.white, bg = c.bg }
    xplr.config.general.style.focused = { fg = c.bg, bg = c.highlight, add_modifiers = { "Bold" } }
    xplr.config.general.style.selected = { fg = c.accent, add_modifiers = { "Italic" } }

    xplr.config.node_types.directory.style = { fg = c.primary, add_modifiers = { "Bold" } }
    xplr.config.node_types.file.style      = { fg = c.white }
    xplr.config.node_types.symlink.style   = { fg = c.highlight, add_modifiers = { "Italic" } }
    xplr.config.node_types.executable.style = { fg = c.hotAccent }

    xplr.config.general.table.header.style = { fg = c.muted }
    xplr.config.general.status_bar.style = { fg = c.gray, bg = c.bg }
  '';

  layoutLua = if cfg.themeVariant == "classic" then "" else (
    if cfg.themeStyle == "basic" then ''
      xplr.config.layouts.builtin.default = {
          "Table",
      }
    '' else ''
      xplr.config.layouts.builtin.default = {
          "Table",
          "HelpMenu",
      }
    ''
  ) + ''
    xplr.config.general.table.columns = {
        { name = " ", field = "icon", width = 2 },
        { name = "Name", field = "name", width = 50 },
        { name = "Size", field = "size", width = 10 },
    }
  '';

  initLua = ''
    -- xplr configuration generated by Nix
    local xplr = xplr

    ${paletteLua}
    ${layoutLua}
  '';

in {
  config = lib.mkIf cfg.enable {
    home.file.".config/xplr/init.lua".text = initLua;
  };
}
