[global]
show_legacy_warning = false
progress_full_character = "━"
progress_empty_character = "─"
progress_prefix = "["
progress_suffix = "]"

[uptime]
prefix = "Uptime:"

[memory]
swap_pos = "below"

[filesystems]

[last_login]
