# Pinchflat lifecycle webhook module
#
# Generates a lifecycle script for Pinchflat that sends media_downloaded
# events to an n8n webhook for transcript processing.
#
# Only videos from channels in the allowedChannels list will trigger webhooks.
#
# Usage:
#   services.pinchflat-lifecycle = {
#     enable = true;
#     webhookUrl = "https://n8n.meskill.farm/webhook/pinchflat-transcript";
#     allowedChannels = [
#       "PBS NewsHour"
#       "CNN"
#     ];
#   };
#
{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.services.pinchflat-lifecycle;

  # Generate the bash array of allowed channels
  channelsArray =
    if cfg.allowedChannels == []
    then ""
    else ''
      # Allowed channels for transcript processing
      ALLOWED_CHANNELS=(
      ${concatMapStringsSep "\n" (ch: "  \"${ch}\"") cfg.allowedChannels}
      )

      # Check if channel is in the allowed list
      is_allowed_channel() {
        local channel="$1"
        for allowed in "''${ALLOWED_CHANNELS[@]}"; do
          if [[ "$channel" == "$allowed" ]]; then
            return 0
          fi
        done
        return 1
      }
    '';

  # Generate the channel check logic
  channelCheckLogic =
    if cfg.allowedChannels == []
    then ""
    else ''

      # Check if this channel is in the allowed list
      if ! is_allowed_channel "$CHANNEL"; then
        log "Channel '$CHANNEL' not in allowed list - skipping"
        exit 0
      fi
    '';

  # Generate the lifecycle script
  # NOTE: Uses plain commands (jq, curl) since this runs INSIDE the Pinchflat container
  # which has these tools at /usr/bin/, not Nix store paths
  lifecycleScript = pkgs.writeTextFile {
    name = "pinchflat-lifecycle";
    executable = true;
    text = ''
      #!/bin/bash
      # Pinchflat lifecycle script for YouTube transcript extraction
      # Sends media_downloaded events to n8n for transcript processing
      #
      # Events: app_init, media_pre_download, media_downloaded, media_deleted
      # This script only handles media_downloaded events with subtitles.
      #
      # Generated by: nix-config (hosts/monolith/pinchflat.nix)
      # Target: n8n workflow "Newsy 3.0 - Ingest - YouTube Transcript"

      set -euo pipefail

      EVENT_TYPE="''${1:-}"
      EVENT_DATA="''${2:-}"

      # Webhook endpoint for n8n
      WEBHOOK_URL="${cfg.webhookUrl}"

      ${channelsArray}

      # Logging helper
      log() {
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] [lifecycle] $1"
      }

      # Only process media_downloaded events
      if [[ "$EVENT_TYPE" != "media_downloaded" ]]; then
        exit 0
      fi

      # Validate we have event data
      if [[ -z "$EVENT_DATA" ]]; then
        log "ERROR: No event data received"
        exit 0
      fi

      # Check if subtitles exist
      SUBTITLE_COUNT=$(echo "$EVENT_DATA" | jq -r '.subtitle_filepaths | length // 0')
      if [[ "$SUBTITLE_COUNT" -eq 0 ]]; then
        TITLE=$(echo "$EVENT_DATA" | jq -r '.title // "unknown"')
        log "No subtitles available for: $TITLE - skipping"
        exit 0
      fi

      # Extract metadata for logging
      TITLE=$(echo "$EVENT_DATA" | jq -r '.title // "unknown"')
      CHANNEL=$(echo "$EVENT_DATA" | jq -r '.source.collection_name // "unknown"')
      VIDEO_ID=$(echo "$EVENT_DATA" | jq -r '.media_id // "unknown"')
      ${channelCheckLogic}

      log "Processing: $TITLE (channel: $CHANNEL, video_id: $VIDEO_ID, subtitles: $SUBTITLE_COUNT)"

      # Send to n8n webhook
      RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$WEBHOOK_URL" \
        -H "Content-Type: application/json" \
        -H "X-Pinchflat-Event: media_downloaded" \
        --max-time 30 \
        -d "$EVENT_DATA" 2>&1) || true

      # Extract HTTP status code (last line)
      HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
      BODY=$(echo "$RESPONSE" | sed '$d')

      if [[ "$HTTP_CODE" == "200" ]] || [[ "$HTTP_CODE" == "201" ]] || [[ "$HTTP_CODE" == "202" ]]; then
        log "SUCCESS: Sent to n8n (HTTP $HTTP_CODE)"
      else
        log "WARNING: n8n returned HTTP $HTTP_CODE - $BODY"
        # Don't fail - Pinchflat should continue even if webhook fails
      fi

      exit 0
    '';
  };
in {
  options.services.pinchflat-lifecycle = {
    enable = mkEnableOption "Pinchflat lifecycle webhook for transcript processing";

    webhookUrl = mkOption {
      type = types.str;
      default = "https://n8n.meskill.farm/webhook/pinchflat-transcript";
      description = "Webhook URL to send media_downloaded events to";
      example = "https://n8n.example.com/webhook/pinchflat";
    };

    allowedChannels = mkOption {
      type = types.listOf types.str;
      default = [];
      description = ''
        List of Pinchflat collection names (channel names) to process for transcription.
        Only videos from these channels will trigger the webhook.
        If empty, ALL channels will be processed.
      '';
      example = [
        "PBS NewsHour"
        "CNN"
        "BBC News"
      ];
    };

    scriptPath = mkOption {
      type = types.path;
      default = lifecycleScript;
      readOnly = true;
      description = "Path to the generated lifecycle script (read-only)";
    };
  };

  config = mkIf cfg.enable {
    # Make the script available as a derivation output
    # The container definition can reference cfg.scriptPath
  };
}
