# Pinchflat lifecycle webhook module
#
# Generates a lifecycle script for Pinchflat that sends media_downloaded
# events to an n8n webhook for YouTube summary processing.
#
# Only videos from channels in the allowedChannels list will trigger webhooks.
#
# Usage:
#   services.pinchflat-lifecycle = {
#     enable = true;
#     webhookUrl = "https://n8h.meskill.farm/webhook/youtube-summary";
#     allowedChannels = [
#       "PBS NewsHour"
#       "CNN"
#     ];
#   };
#
{
  config,
  lib,
  pkgs,
  ...
}:
with lib; let
  cfg = config.services.pinchflat-lifecycle;

  # Generate the bash array of allowed channels
  channelsArray =
    if cfg.allowedChannels == []
    then ""
    else ''
      # Allowed channels for transcript processing
      ALLOWED_CHANNELS=(
      ${concatMapStringsSep "\n" (ch: "  \"${ch}\"") cfg.allowedChannels}
      )

      # Check if channel is in the allowed list
      is_allowed_channel() {
        local channel="$1"
        for allowed in "''${ALLOWED_CHANNELS[@]}"; do
          if [[ "$channel" == "$allowed" ]]; then
            return 0
          fi
        done
        return 1
      }
    '';

  # Generate the channel check logic
  channelCheckLogic =
    if cfg.allowedChannels == []
    then ""
    else ''

      # Check if this channel is in the allowed list
      if ! is_allowed_channel "$CHANNEL"; then
        log "Channel '$CHANNEL' not in allowed list - skipping"
        exit 0
      fi
    '';

  # Generate the lifecycle script
  # NOTE: Uses plain commands (jq, curl, awk) since this runs INSIDE the Pinchflat container
  # which has these tools at /usr/bin/, not Nix store paths
  lifecycleScript = pkgs.writeTextFile {
    name = "pinchflat-lifecycle";
    executable = true;
    text = ''
      #!/bin/bash
      # Pinchflat lifecycle script for YouTube summary processing
      # Sends media_downloaded events to n8n for transcript extraction and summarization
      #
      # Events: app_init, media_pre_download, media_downloaded, media_deleted
      # This script only handles media_downloaded events with subtitles.
      #
      # Generated by: nix-config (hosts/monolith/pinchflat.nix)
      # Target: n8n workflow "YouTube Summary"

      set -euo pipefail

      EVENT_TYPE="''${1:-}"
      EVENT_DATA="''${2:-}"

      # Webhook endpoint for n8n
      WEBHOOK_URL="${cfg.webhookUrl}"

      ${channelsArray}

      # Logging helper
      log() {
        echo "[$(date '+%Y-%m-%d %H:%M:%S')] [lifecycle] $1"
      }

      # Parse SRT/VTT file with deduplication of consecutive lines
      # Removes timestamps, indices, tags, and deduplicates overlapping subtitle text
      parse_srt() {
        awk '
          BEGIN { prev = ""; result = "" }
          {
            gsub(/\r/, "")
            gsub(/^[ \t]+|[ \t]+$/, "")
            if ($0 == "") next
            if ($0 == "WEBVTT") next
            if ($0 ~ /^[0-9]+$/) next
            if ($0 ~ /-->/) next
            if ($0 ~ /^NOTE/) next
            if ($0 ~ /^STYLE/) next
            gsub(/<[^>]*>/, "")
            gsub(/\{[^}]*\}/, "")
            gsub(/^[ \t]+|[ \t]+$/, "")
            if ($0 == "") next
            if ($0 != prev) {
              if (result != "") result = result " " $0
              else result = $0
              prev = $0
            }
          }
          END { print result }
        ' "$1"
      }

      # Only process media_downloaded events
      if [[ "$EVENT_TYPE" != "media_downloaded" ]]; then
        exit 0
      fi

      # Validate we have event data
      if [[ -z "$EVENT_DATA" ]]; then
        log "ERROR: No event data received"
        exit 0
      fi

      # Extract metadata from event data
      TITLE=$(echo "$EVENT_DATA" | jq -r '.title // "unknown"')
      CHANNEL=$(echo "$EVENT_DATA" | jq -r '.source.collection_name // "unknown"')
      VIDEO_ID=$(echo "$EVENT_DATA" | jq -r '.media_id // "unknown"')
      VIDEO_FILEPATH=$(echo "$EVENT_DATA" | jq -r '.media_filepath // ""')
      DESCRIPTION=$(echo "$EVENT_DATA" | jq -r '.description // ""')
      ORIGINAL_URL=$(echo "$EVENT_DATA" | jq -r '.original_url // .webpage_url // ""')
      UPLOAD_DATE=$(echo "$EVENT_DATA" | jq -r '.upload_date // ""')
      DURATION_SECONDS=$(echo "$EVENT_DATA" | jq -r '.duration // 0')

      # Try to find subtitle file
      SUBTITLE_FILE=""

      # First try subtitle_filepaths from event data
      SUBTITLE_COUNT=$(echo "$EVENT_DATA" | jq -r '.subtitle_filepaths | if type == "array" then length else 0 end // 0')
      if [[ "$SUBTITLE_COUNT" -gt 0 ]]; then
        CANDIDATE=$(echo "$EVENT_DATA" | jq -r '.subtitle_filepaths[0] // ""')
        if [[ -n "$CANDIDATE" ]] && [[ -f "$CANDIDATE" ]]; then
          SUBTITLE_FILE="$CANDIDATE"
          log "Found subtitle in event data: $SUBTITLE_FILE"
        else
          log "Event data subtitle path invalid or missing: $CANDIDATE"
        fi
      fi

      # Fallback: Look for .srt file next to the video file
      if [[ -z "$SUBTITLE_FILE" ]] && [[ -n "$VIDEO_FILEPATH" ]]; then
        VIDEO_DIR=$(dirname "$VIDEO_FILEPATH")
        VIDEO_BASE=$(basename "$VIDEO_FILEPATH")
        VIDEO_NAME="''${VIDEO_BASE%.*}"

        # Search for .en.srt or .srt file matching the video name
        if [[ -f "$VIDEO_DIR/$VIDEO_NAME.en.srt" ]]; then
          SUBTITLE_FILE="$VIDEO_DIR/$VIDEO_NAME.en.srt"
          log "Found subtitle on disk: $SUBTITLE_FILE"
        elif [[ -f "$VIDEO_DIR/$VIDEO_NAME.srt" ]]; then
          SUBTITLE_FILE="$VIDEO_DIR/$VIDEO_NAME.srt"
          log "Found subtitle on disk: $SUBTITLE_FILE"
        else
          # Try to find any .srt file with matching prefix
          FOUND_SRT=$(find "$VIDEO_DIR" -maxdepth 1 -name "$VIDEO_NAME*.srt" -type f 2>/dev/null | head -n1)
          if [[ -n "$FOUND_SRT" ]]; then
            SUBTITLE_FILE="$FOUND_SRT"
            log "Found subtitle on disk (pattern match): $SUBTITLE_FILE"
          fi
        fi
      fi

      # Skip if no subtitle found
      if [[ -z "$SUBTITLE_FILE" ]] || [[ ! -f "$SUBTITLE_FILE" ]]; then
        log "No subtitles available for: $TITLE - skipping"
        exit 0
      fi
      ${channelCheckLogic}

      log "Processing: $TITLE (channel: $CHANNEL, video_id: $VIDEO_ID, subtitle: $SUBTITLE_FILE)"

      # Parse and deduplicate transcript
      TRANSCRIPT_TEXT=$(parse_srt "$SUBTITLE_FILE")
      TRANSCRIPT_LENGTH=''${#TRANSCRIPT_TEXT}

      if [[ "$TRANSCRIPT_LENGTH" -eq 0 ]]; then
        log "WARNING: Parsed transcript is empty for: $TITLE - skipping"
        exit 0
      fi

      log "Extracted transcript: $TRANSCRIPT_LENGTH characters (deduplicated)"

      # Build payload with all required fields for n8n YouTube Summary workflow
      PAYLOAD=$(jq -n \
        --arg title "$TITLE" \
        --arg media_id "$VIDEO_ID" \
        --arg media_filepath "$VIDEO_FILEPATH" \
        --arg subtitle_filepath "$SUBTITLE_FILE" \
        --arg transcript "$TRANSCRIPT_TEXT" \
        --arg channel "$CHANNEL" \
        --arg description "$DESCRIPTION" \
        --arg original_url "$ORIGINAL_URL" \
        --arg upload_date "$UPLOAD_DATE" \
        --argjson duration "$DURATION_SECONDS" \
        '{
          title: $title,
          media_id: $media_id,
          media_filepath: $media_filepath,
          subtitle_filepaths: [$subtitle_filepath],
          subtitle_filepath: $subtitle_filepath,
          transcript_text: $transcript,
          duration_seconds: $duration,
          description: $description,
          original_url: $original_url,
          upload_date: $upload_date,
          source: {collection_name: $channel}
        }')

      # Send to n8n webhook
      RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$WEBHOOK_URL" \
        -H "Content-Type: application/json" \
        -H "X-Pinchflat-Event: media_downloaded" \
        --max-time 60 \
        -d "$PAYLOAD" 2>&1) || true

      # Extract HTTP status code (last line)
      HTTP_CODE=$(echo "$RESPONSE" | tail -n1)
      BODY=$(echo "$RESPONSE" | sed '$d')

      if [[ "$HTTP_CODE" == "200" ]] || [[ "$HTTP_CODE" == "201" ]] || [[ "$HTTP_CODE" == "202" ]]; then
        log "SUCCESS: Sent to n8n (HTTP $HTTP_CODE) - $BODY"
      else
        log "WARNING: n8n returned HTTP $HTTP_CODE - $BODY"
        # Don't fail - Pinchflat should continue even if webhook fails
      fi

      exit 0
    '';
  };
in {
  options.services.pinchflat-lifecycle = {
    enable = mkEnableOption "Pinchflat lifecycle webhook for YouTube summary processing";

    webhookUrl = mkOption {
      type = types.str;
      default = "https://n8h.meskill.farm/webhook/youtube-summary";
      description = "Webhook URL to send media_downloaded events to";
      example = "https://n8n.example.com/webhook/youtube-summary";
    };

    allowedChannels = mkOption {
      type = types.listOf types.str;
      default = [];
      description = ''
        List of Pinchflat collection names (channel names) to process for transcription.
        Only videos from these channels will trigger the webhook.
        If empty, ALL channels will be processed.
      '';
      example = [
        "PBS NewsHour"
        "CNN"
        "BBC News"
      ];
    };

    scriptPath = mkOption {
      type = types.path;
      default = lifecycleScript;
      readOnly = true;
      description = "Path to the generated lifecycle script (read-only)";
    };
  };

  config = mkIf cfg.enable {
    # Make the script available as a derivation output
    # The container definition can reference cfg.scriptPath
  };
}
