# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  inputs,
  ...
}: {
  imports = [
    inputs.hardware.nixosModules.framework-desktop-amd-ai-max-300-series
  ];

  nixpkgs.hostPlatform = "x86_64-linux";

  services.fwupd.enable = true;
  hardware.enableRedistributableFirmware = true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  boot.loader.systemd-boot.enable = lib.mkDefault true;
  boot.loader.efi.canTouchEfiVariables = true;

  swapDevices = [];

  # allow remote deploy on aarch64 systems
  boot.binfmt.emulatedSystems = ["aarch64-linux"];

  networking.firewall.enable = true;
  networking.nftables.enable = true;
  networking.useDHCP = lib.mkDefault false;
  networking.wireless.enable = lib.mkDefault false;
  networking.networkmanager.enable = false;
  systemd.network.enable = true;
  systemd.network.networks."10-ethernet-dhcp" = {
    enable = true;
    matchConfig.Name = "enp191s0";
    networkConfig = {
      DHCP = "ipv4";
      IPv6AcceptRA = true; # Optional: for IPv6 SLAAC
    };
  };

  # Enable Wake-on-LAN for the ethernet interface
  systemd.network.links."10-ethernet-wol" = {
    enable = true;
    matchConfig.OriginalName = "enp191s0";
    linkConfig = {
      WakeOnLan = "magic";
    };
  };
}
